#!/bin/bash

read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (hari): " masaaktif

MYIP=$(wget -qO- ipv4.icanhazip.com)
IPV4=$(dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com)
IP=$(dig +short https://diagnostic.opendns.com/myip)

useradd -e $(date -d "$masaaktif days" +"%Y-%m-%d") -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n" | passwd $Login &>/dev/null
echo -e ""
echo -e "====Information SSH Account===="
echo -e "Host: $MYIP"
echo -e "Port OpenSSH   : 22,143"
echo -e "Port Dropbear  : 80,444"
echo -e "Port SSL/TLS   : 443"
echo -e "Port Squid     : 8080,3128"
echo -e "Config OpenVPN (TCP 1194): http://$MYIP:81/client.ovpn"
echo -e "Username: $Login "
echo -e "Password: $Pass"
echo -e "-----------------------------"
echo -e "Aktif Sampai: $exp"
echo -e "============================="
echo -e "Dark-IT"
