#!/bin/bash

read -p "Username SSH should be deleted : " User

if getent passwd $User >/dev/null 2>&1; then
        userdel $User
        echo -e "User $User deleted successfully."
else
        echo -e "FAILED: User $User not found."
fi
